### ISSUE TITLE
Support the EPICS archiver appliance

### ISSUE THREAD

**Issue by klauer** [slaclab/pytmc#139]
From Murali, we now know that:

```
Cron jobs are in place running processRequestFile.py, so just make sure your IOC build and
release process installs archive request files to $IOC_DATA/$IOC_NAME/archive/*.archive w/ syntax
MY:PV:NAME    period    [ type ]
period can be integer or floating point
type is optional, either monitor or scan, defaults to scan.
```

We can create our own `info` tags per-record and generate these files. Or `pytmc` could output them directly.

**Comment by klauer** [comment]
Default will be `scan` `1s`, except for waveforms

**Comment by klauer** [comment]
(*) Waveforms of larger than a threshold, that is

**Comment by klauer** [comment]
`archive: {1s/1hz} {scan/monitor}`
Default: `archive 1s scan`

Examples:
`archive: 1s scan`
`archive: 1hz monitor`
`archive: 1s` (=scan)

**Comment by n-wbrown** [comment]
Notes from discussion with @klauer 

Reuse the `bin.bin.process method for generating a list of records. 

Add archive file generation onto the `db` command line tool. When an output file is specified, the archive file will be generated by default.
