### ISSUE TITLE
Pinned global datatypes have a different property name

### ISSUE THREAD

**Issue by n-wbrown** [slaclab/pytmc#140]
`plcAttribute_pytmc` is inserted into the `Property/Name` for a pinned global data type. 

Our first step is to determine if this is intended Beckhoff behavior. If is, we support the new property name. If it is not an intended we create a temporary fix that can easily be removed if/when beckhoff patches the behavior.

**Comment by slacAWallace** [comment]
Can we prioritize this before finding out if it's intended? Nate is out until next week.

**Comment by n-wbrown** [comment]
I can start working on a patch tomorrow.

**Comment by n-wbrown** [comment]
closed by #144
