### ISSUE TITLE
Enhance debug tool to show chains with incomplete pragmas

### ISSUE THREAD

**Issue by klauer** [slaclab/pytmc#147]
e.g., a chain of:
`symbol` `struct` `struct.member`
where the `symbol` has a pragma, but nothing in `struct` has a pragma, it would be useful to see that somehow.

**Comment by n-wbrown** [comment]
Notes from conversation w/ @klauer:

 - Only the debug tool needs changes
 - add a category (in addition to chains/records) for not-rendered records into the top left select bar
