### ISSUE TITLE
pytmc summary --boxes displays anomalous numbering order

### ISSUE THREAD

**Issue by n-wbrown** [slaclab/pytmc#148]
Using `pytmc summary --boxes` on the ArbiterPLC project included for tests yields the following:

I have not yet ruled out issues with the `.sln` as the source of the issue.

```
    1.) Term 1 (EK1200)
    2.) PMPS_FFO
    7.) PMPS_BC
    8.) PMPS_CLTS
    3.) Term 3 (EK1122)
    5.) SubSysPLC1
    4.) SubSysPLC2
    6.) Term 6 (EK1110)
```

**Comment by klauer** [comment]
😆 Looks like project doesn't store the IDs in order. We need a sort in the `show_boxes` section of summary.py.
