### ISSUE TITLE
Conda Recipe Missing epics-pypdb Dependency

### ISSUE THREAD

**Issue by ZLLentz** [slaclab/pytmc#149]
See title

**Comment by klauer** [comment]
We're missing pypdb on conda entirely :(

**Comment by ZLLentz** [comment]
:(

**Comment by klauer** [comment]
Paging conda-forge expert @hhslepicka

**Comment by hhslepicka** [comment]
I asked Michael to cut an official release of this package. When we have it I will add it to conda-forge.

**Comment by ZLLentz** [comment]
Ok, so actually the `pypdb` dependency is listed in the conda recipe, but the package requires the dependency to explicitly be called `epics-pypdb` when run via the `pytmc` script that gets built in a python environment. This is a script you never see unless you build/install the package. I'm going to make a PR for testing that script.

**Comment by hhslepicka** [comment]
A conda recipe was added to https://github.com/pcdshub/epics-pypdb so it can now be built locally.
Also, once this PR ( https://github.com/conda-forge/staged-recipes/pull/10408 ) is merged we will have it available via `conda-forge` as well.

**Comment by ZLLentz** [comment]
Thank you! Should I rebuild locally now or did you do this too?

**Comment by hhslepicka** [comment]
No... I did not build it locally... 😞
