### ISSUE TITLE
Path loading still isn't quite right (independent project files)

### ISSUE THREAD

**Issue by klauer** [slaclab/pytmc#187]
Leaving everything to be "independent" in TwinCAT, pytmc has no issue on any project I've found so far:

![image](https://user-images.githubusercontent.com/5139267/75398120-97f19580-58ad-11ea-9e43-d838187599ea.png)

Changing these values or manually tweaking a file's status as an external ("independent project file") can cause the parser to fail to find the file:

<img width="361" alt="image" src="https://user-images.githubusercontent.com/5139267/75398182-ba83ae80-58ad-11ea-874d-2384cc2e7371.png">

At some point, we should generate all feasible variants of projects and ensure that pytmc can load them all.

**Comment by slacAWallace** [comment]
I ran into this, or something similar today.

https://travis-ci.com/github/pcdshub/lcls-plc-kfe-arbiter/builds/174854952

**Comment by klauer** [comment]
I think this did it: https://github.com/slaclab/pytmc/pull/228 (fingers crossed)
