### ISSUE TITLE
DESC should appear in project summary for records

### ISSUE THREAD

**Issue by slacAWallace** [slaclab/pytmc#197]
It would be nice if DESC appeared next to records in the project summary.

**Comment by klauer** [comment]
I can't transfer this issue across organizations (slaclab -> pcdshub), but will open a related issue there.

For reference, this is what generates that webpage summary:
https://github.com/pcdshub/pcds-ci-helpers/blob/3888546364f12d25ecc885b382215b0b79fc139e/travis/tc3_linter.sh#L68

**Comment by klauer** [comment]
Description is now included in webpage summary as part of ads-deploy. e.g.,

<img width="677" alt="image" src="https://user-images.githubusercontent.com/5139267/99580860-d62b6980-2994-11eb-8716-a62a0ffc956d.png">
