### ISSUE TITLE
Command line interface

### ISSUE THREAD

**Issue by jsheppard95** [slaclab/pytmc#20]
The current installation process uses (in setup.py) the line:
`scripts = ['bin/xmltranslate', 'bin/makerecord']`
requiring the user to run the application as:
`python bin/makerecord --help`

Instead one could use "entry points", for example:
`entry_points={'console_scripts': ['pytmc=<cli_script>']})`

**Comment by n-wbrown** [comment]
These concerns are addressed in PR #21. The primary command is now `pytmc`. Documentation has been updated to reflect these changes and improve readability. Please let me know if you are able to install and use the package successfully now.

**Comment by jsheppard95** [comment]
Just re-installed and works great! Thanks @n-wbrown !
