### ISSUE TITLE
pytmc --help fails if QT is not installed. 

### ISSUE THREAD

**Issue by n-wbrown** [slaclab/pytmc#201]
Instructions for qt installation is not documented or included in the requirements files.

**Comment by klauer** [comment]
Hmm, it should get picked up by the following:

https://github.com/slaclab/pytmc/blob/4442d24171cc20420abdb485872c9f954dedd64a/pytmc/bin/pytmc.py#L41-L46

which notes why you can't use a specific command (like `pytmc debug`) because of a missing import.

Which specific import is it bailing on?
