### ISSUE TITLE
Waveform handling

### ISSUE THREAD

**Issue by klauer** [slaclab/pytmc#231]
Some PLC projects need the following pragma for waveforms:

```
archive: no
```

The default update rate for all waveforms should _probably_ by default be proportional to `exp(length)` (or something along those lines)..

**Comment by klauer** [comment]
Default, instead, should be:

```
field: APST On Change
field: MPST On Change
```

10 years of EPICS and I'm still discovering (maybe rediscovering?) some basics 🤷‍♂️

**Comment by ZLLentz** [comment]
I had no idea this was a thing
