### ISSUE TITLE
FullBuild breaks when  "==" is used in place of "is"

### ISSUE THREAD

**Issue by n-wbrown** [slaclab/pytmc#30]
The test_TmcFile_fullbuild test fails when the "==" is used in place of "is". This does not appear to interfere w/ primary functionality but still merits investigation. 

See this [TODO](https://github.com/slaclab/pytmc/pull/28/commits/1344a13c0b4a032cda50430ec36c039e231588e7) note for details. 

Issue originally spotted by @klauer.

**Comment by klauer** [comment]
No longer applies after the tcparse project merge.
