### ISSUE TITLE
Records generated for partially specified tmc entries

### ISSUE THREAD

**Issue by klauer** [slaclab/pytmc#38]
Pragma from `XtesSxrPlc.tmc`, `TV2K4_VGC_1:ErrMsg`:
```
    pv: ErrMsg;
    io: o;
```

Generated record:
```c
record(,"TV2K4_VGC_1:ErrMsg"){
  field(PINI, "1")
  field(TSE, -2)
  field(OUT, "@asyn($(PORT),0,1)ADSPORT=851/GVL_DEVICES.TV2K4_VGC_1.iq_stValve.sErrorMessage=")
  field(SCAN, "Passive")
}
```

**Comment by n-wbrown** [comment]
Rendered entry lacks DTYP field.

**Comment by n-wbrown** [comment]
sErrorMessage is a STRING(80) subitem based upon this [.tmc file](https://github.com/craigmcchesney/XTES-SXR-vacuum-PLC-prototype/blob/c275fe633f27adfab86f31c001725f9b06342b52/XtesSxrPlcProto/XtesSxrPlc/XtesSxrPlc.tmc).
