### ISSUE TITLE
Support Autosave and use sensible defaults

### ISSUE THREAD

**Issue by teddyrendahl** [slaclab/pytmc#41]
I think it is crucial to allow a user to request that a specific PV created by a `pytmc` database file is archived or autosaved. Ideally this is just an additional pragma, but putting it somewhere where we can make sure that the built IOC respects these takes some thought.

**Comment by klauer** [comment]
For autosave:
* `info` nodes should be used. Example from the [documentation](https://epics.anl.gov/bcda/synApps/autosave/autoSaveRestore_R5-6-1.html):
```
record(ao, "$(P)test1") {
  field(DTYP, "Soft Channel")
  info(autosaveFields, "PREC EGU DESC")
  info(autosaveFields_pass0, "VAL")
}
From this information, makeAutosaveFiles() will write the following two files:

info_settings.req
$(P)test1.PREC
$(P)test1.EGU
$(P)test1.DESC

info_positions.req
$(P)test1.VAL
This function can be called at any time after iocInit().
```
* Additional fields could be set on a per-record basis
* Likely all setpoint .VAL should be saved by default

**Comment by klauer** [comment]
As #137 will tackle autosave, I'm going to split the archiver into a separate issue.
