### ISSUE TITLE
Add USINT support

### ISSUE THREAD

**Issue by klauer** [slaclab/pytmc#58]

**Comment by ZLLentz** [comment]
USINT didn't work for Jackson and I. After switching to SINT it started working. We should investigate further.

**Comment by n-wbrown** [comment]
Reopening this issue as per @ZLLentz's comment

**Comment by ZLLentz** [comment]
`TEST:FILTERWHEEL:GETPOS devAsynUInt32Digital::initCommon invalid INST_IO Must be asynMask(<port> <addr> <mask> <timeout>)userParams`

**Comment by klauer** [comment]
Oops! This bug will apply to all `asynUint32Digital`s (BYTE, USINT, WORD, UINT, DWORD). 

Will need to adjust `INP`/`OUT` to use `asynMask` instead of `@asyn`.

**Comment by teddyrendahl** [comment]
May have been fixed in #65, waiting for live test to confirm.

**Comment by klauer** [comment]
Confirmed working locally - 8-bit ints USINT, SINT, INT
