### ISSUE TITLE
Decide on pattern for setpoint/readback records

### ISSUE THREAD

**Issue by klauer** [slaclab/pytmc#64]
With asyn [R4-26](https://epics.anl.gov/modules/soft/asyn/R4-26/RELEASE_NOTES.html), a new option to allow a record to act as both a setpoint and readback was introduced:

> Added capability for output records to update their values with a callback from the driver. 
> This is enabled by adding the following info tag to the output record:
> `info(asyn:READBACK, "1")`
> The output record value will update any time the driver does a callback with a new value. 

pytmc currently uses this, as it only requires generating one record for a specific chain.

While convenient for record generation, the above goes against the pattern used almost everywhere else in the EPICS world, where there are distinct records for setpoint and their associated readbacks (`_RBV`). 

Mark, as the primary author of asyn, outlines rather nicely some arguments against using the new `asyn:READBACK` functionality in this tech-talk post: https://epics.anl.gov/tech-talk/2016/msg00157.php .

We should decide which style we're going to use going forward and stick with it consistently. 

At least @n-wbrown, @zllentz, @teddyrendahl should weigh in before we proceed.
My vote is on separating setpoint/readback, though it will be more work.

**Comment by teddyrendahl** [comment]
I too vote for separate readbacks and setpoints. Keeping these things compartmentalized makes it easier to identify discontinuities between our EPICS instructions and the PLC state
