### ISSUE TITLE
Split fixed size Twincat array into multiple records

### ISSUE THREAD

**Issue by teddyrendahl** [slaclab/pytmc#80]
If you have a small fixed size Twincat array it could be helpful to instead of creating an EPICS Waveform record, create a separate record for each index.

**Comment by klauer** [comment]
This came up with PMPS, as there may be a list of (long) strings indicating the cause of a fast fault. We'd want these exposed to EPICS for diagnostic information.

**Comment by klauer** [comment]
This works now as of #126
